### PR TITLE
fix: export HTTP_AUTH to github env

### PR DESCRIPTION
**Pull request by 89luca89**
it's useful for some situations where we need auth for packages or whatnot

### CODE REVIEW

**Comment by k4leung4** [comment]
> it's useful for some situations where we need auth for packages or whatnot

can you make this configurable, as some user may not want to have it exported?

**Comment by 89luca89** [comment]
> > it's useful for some situations where we need auth for packages or whatnot
> 
> can you make this configurable, as some user may not want to have it exported?

Done as requested :saluting_face:

**Review by k4leung4 — APPROVED** [review]
thank you

**Comment by 89luca89** [comment]
Thanks!

**Pull request merged**
